version: '3'
services:
    mydb:
        image: mysql:5.6
        hostname: mydb
        container_name: mydb-server
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: skyinfo
            MYSQL_DATABASE: myimages
        ports:
            - '3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
        networks: 
            - my-app-network

    node1:
        build:
            dockerfile: ./docker/app-server.dockerfile
            context: .
        image: armandoss/app-server
        container_name: app-server-1
        ports:
            - "5000:5000"
        networks: 
            - my-app-network
        depends_on:
            - "mydb"

networks: 
    my-app-network:
        driver: bridge